#!/bin/sh
#########################################################################
#                                                                       #
#                       __   __    ____ _____ ____                      #
#                       \ \ / /_ _/ ___|_   _|___ \                     #
#                        \ V / _` \___ \ | |   __) |                    #
#                         | | (_| |___) || |  / __/                     #
#                         |_|\__,_|____/ |_| |_____|                    #
#                                                                       #
#                 Module for the IBM DB2 Universal Database             #
#                                                                       #
#########################################################################
#
#   Copyright (C) 2003  SUSE LINUX AG, Nuernberg, Germany
#
#   Author:     David Strbac <strbac@suse.de>
#
#
#   This file is part of yast2_db2setup.
#
#   yast2_db2setup is free software; you can redistribute it and/or
#   modify it under the terms of the GNU General Public License as
#   published by the Free Software Foundation; either version 2 of the
#   License, or (at your option) any later version.
#
#   yast2_db2setup is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
#   General Public License for more details.
#
#   You should have received a copy of the GNU General Public License
#   along with yast2_db2setup; if not, write to the Free Software
#   Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307
#   USA
#
#
#########################################################################
#                                                                       #
#   FILE:     yast2_db2setup                                            #
#                                                                       #
#   SUMMARY:  wrapper for the YaST2 DB2 installation module             #
#                                                                       #
#########################################################################



VERSION='$Id$'



function display_help()
{
	cat <<-EOF
	$(basename $0), version $(set $VERSION; echo $3 $4)
	Usage: $(basename $0) [GNU long option] [option]
	-h, --help                 display this message
	-l, --logfile <file>       set logfile (default is stdout) 
	-d, --debug                enable debugging
	-v, --version              display version
	-s, --server [ncurses|qt]  specify YaST server
	EOF
}



function display_version()
{
	echo "VERSION:  $VERSION"
}





ARG=$(getopt -n yast2_db2setup -o hl:dvs: --long help,logfile:,debug,version,server: -- "$@")

[ $? != 0 ] && echo "aborting ..." >&2 && exit 1

eval set -- "$ARG"

while [ $# != 0 ] ; do
	case $1 in
		-h|--help)	display_help; exit;;
		-l|--logfile)	LOGFILE=$2 shift 2;;
		-d|--debug)	export Y2DEBUG=1; shift;;
		-v|--version)	display_version; exit;;
		-s|--server)	Y2_SERVER=$2 shift 2;;
		--)		shift; break;;
		*)		echo "Internal error at $LINENO" >&2 ; exit 1 ;;
	esac
done

echo "changing directory to $(pwd)/$(dirname $0)"
cd $(dirname $0)

# enable debugging
[ $Y2DEBUG ] && set -x

# YCP module
DB2_INSTALL="./db2_install.ycp"

# if YaST server is not specified on the command line ...
[ ! $Y2_SERVER ] &&
{
	# ... try to find out if it's possible to use qt server.
	[ ! $DISPLAY ] && Y2_SERVER="ncurses" || Y2_SERVER="qt"
}

# default value (log to stdout if we use the qt server)
if [ $Y2_SERVER = "qt" ]; then
	[ ! $LOGFILE ] && LOGFILE="-"
else
	[ ! $LOGFILE ] && LOGFILE=/dev/null
fi

# YaST binary
Y2BASE="/usr/lib/YaST2/bin/y2base -l $LOGFILE"

# DB2 license file
export DB2_LICENSE="../ese_LI_en"

# DB2 log file
export DB2_LOG="/tmp/db2setup.log"

# start YaST
exec $Y2BASE $DB2_INSTALL $Y2_SERVER

